import { ShopItem, Skin, Contact } from './types';

export const DEFAULT_CONTACTS: Contact[] = [
  { id: 'maksim', name: 'Максим Сурнин', avatar: 'М' },
  { id: 'roma', name: 'Роман Цветков', avatar: 'Р' },
  { id: 'evgeny', name: 'Ощепков Евгений', avatar: 'О' },
  { id: 'elizaveta', name: 'Елизавета Кривошеина', avatar: 'Е' },
];

export const SKINS: Skin[] = [
  {
    id: 'default',
    name: 'Обычный Воробьёв',
    price: 0,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vorobyov&backgroundColor=e6f4ea'
  },
  {
    id: 'businessman',
    name: 'Бизнесмен',
    price: 100000,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Business&backgroundColor=b6e3f4&accessories=sunglasses&clothes=blazerAndShirt'
  },
  {
    id: 'mafia',
    name: 'Мафиози',
    price: 200000,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mafia&backgroundColor=ffdfbf&accessories=kurt&clothes=collarAndSweater'
  },
  {
    id: 'cyborg',
    name: 'Киборг',
    price: 500000,
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Cyborg&backgroundColor=c0aede'
  },
  {
    id: 'golden',
    name: 'Золотой Воробьёв',
    price: 1000000,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Golden&backgroundColor=fef08a&accessories=prescription02&clothes=hoodie'
  }
];

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'water',
    name: 'Вода «Шишкин Лес»',
    description: '+1 ₽/клик',
    basePrice: 50,
    type: 'click',
    value: 1,
    icon: 'droplet',
    category: 'drinks',
  },
  {
    id: 'fries',
    name: 'Картофель фри',
    description: '+2 ₽/сек',
    basePrice: 150,
    type: 'passive',
    value: 2,
    icon: 'fries',
    category: 'food',
  },
  {
    id: 'hotdog',
    name: 'Хот-дог',
    description: '+5 ₽/клик',
    basePrice: 500,
    type: 'click',
    value: 5,
    icon: 'hotdog',
    category: 'food',
  },
  {
    id: 'nuggets',
    name: 'Наггетсы',
    description: '+10 ₽/сек',
    basePrice: 1200,
    type: 'passive',
    value: 10,
    icon: 'nuggets',
    category: 'food',
  },
  {
    id: 'burger',
    name: 'Бургер',
    description: '+25 ₽/клик',
    basePrice: 3000,
    type: 'click',
    value: 25,
    icon: 'burger',
    category: 'food',
  },
  {
    id: 'pizza',
    name: 'Пицца',
    description: '+50 ₽/сек',
    basePrice: 8000,
    type: 'passive',
    value: 50,
    icon: 'pizza',
    category: 'food',
  },
  {
    id: 'tea',
    name: 'Чай Улун',
    description: '+100 ₽/клик',
    basePrice: 15000,
    type: 'click',
    value: 100,
    icon: 'coffee',
    category: 'drinks',
  },
  {
    id: 'huawei',
    name: 'Смартфон Huawei',
    description: '+200 ₽/сек',
    basePrice: 35000,
    type: 'passive',
    value: 200,
    icon: 'smartphone',
    category: 'tech',
  },
  {
    id: 'book_xi',
    name: 'Цитатник Си',
    description: '+500 ₽/клик',
    basePrice: 75000,
    type: 'click',
    value: 500,
    icon: 'book',
    category: 'misc',
  },
  {
    id: 'ticket_bj',
    name: 'Билет в Пекин',
    description: '+1000 ₽/сек',
    basePrice: 150000,
    type: 'passive',
    value: 1000,
    icon: 'ticket',
    category: 'misc',
  },
  {
    id: 'pooh',
    name: 'Плюшевый медведь',
    description: '+2500 ₽/клик',
    basePrice: 300000,
    type: 'click',
    value: 2500,
    icon: 'ghost',
    category: 'misc',
  },
  {
    id: 'dragon',
    name: 'Статуя Дракона',
    description: '+5000 ₽/сек',
    basePrice: 1000000,
    type: 'passive',
    value: 5000,
    icon: 'flame',
    category: 'misc',
  },
];

export const DICT: Record<string, string> = {
  'Доход': '收入',
  'Клик': '点击',
  'За клик': '每次点击',
  'Соц. рейтинг': '社会信用',
  'Кошка-жена': '猫老婆',
  'Миска риса': '一碗饭',
  'Витрина': '商店',
  'Переводы': '转账',
  'Профиль': '个人资料',
  'Главная': '主页',
  'Приказ:': '命令：',
  'Контакты': '联系人',
  'Сумма перевода': '转账金额',
  'Перевести': '发送',
  'Скины': '皮肤',
  'Надеть': '装备',
  'Надето': '已装备',
  'Купить': '买',
  'ВоробьOFF': '沃罗比OFF',
  'История': '历史',
  'Ничего нет': '这里什么都没有',
  'Цена:': '价格：',
  'Штраф от Партии': '党的罚款',
  'Вы разочаровали партию': '你让党失望了',
  'Партия разочарована!': '党很失望！',
  'Партия в ярости!': '党很生气！',
  'Партия гордится вами!': '党为你感到骄傲！',
  'Партия требует купить:': '党要求购买：',
  'Время вышло!': '时间到了！',
  'Партия довольна вашей покорностью!': '党对你的顺从感到满意！',
  'Партия изменила язык!': '党改变了语言！',
  'Язык восстановлен': '语言已恢复',
  'Партия недовольна': '党不满意',
  'Ваш социальный рейтинг упал до нуля. Вы отправляетесь в лагерь перевоспитания.': '您的社会信用已降至零。您将被送往再教育营。',
  'Начать заново': '重新开始',
  'Недавние': '最近的',
  'По номеру (СБП)': '按号码 (SBP)',
  'Кому перевести': '转给谁',
  'Доступно:': '可用：',
  'Имя и Фамилия получателя': '收款人姓名',
  'Перевести по СБП': '通过 SBP 转账',
  'История операций': '操作历史',
};

export const t = (text: string, lang: 'ru' | 'zh') => lang === 'zh' ? (DICT[text] || text) : text;

